# Python for Data Analytis

# NUMPY LEARNING

## What is NumPy?
NumPy (Numerical Python) is a Python library used for fast numerical computations and array operations.

## Why NumPy?
- Fast computation
- Less memory usage
- Mathematical operations
- Data Analysis & Machine Learning

## Features
- 1D, 2D, 3D Arrays
- Universal Functions (ufuncs)
- Statistical Functions
- Matrix Operations
- Random Number Generation
- Broadcasting

## Common Functions
- `np.array()` – Create array
- `np.arange()` – Generate sequence
- `np.reshape()` – Change shape
- `np.sqrt()` – Square root
- `np.exp()` – Exponential
- `np.log()` – Natural log
- `np.sin()` – Sine
- `np.cos()` – Cosine
- `np.mean()` – Average
- `np.max()` – Maximum
- `np.min()` – Minimum

## Applications
- Data Analysis
- Machine Learning
- Scientific Computing
- Image Processing

In [10]:
import numpy as np
##creating Array using NumPy

## Create 1D array

arr01=np.array([1, 2, 3, 4, 5])
print(arr01)

## chceking the type 

print(type(arr01))

## checking shape 

print(arr01.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [21]:
##(1Row, 5Column)
arr02=np.array([1, 2, 3, 4, 5])
arr02.reshape(1,5)

[1 2 3 4 5]


array([[1, 2, 3, 4, 5]])

In [24]:
##(5Row, 1Column)
arr02=np.array([1, 2, 3, 4, 5])
arr02.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [18]:
## 2D array 
arr02=np.array([[1, 2, 3, 4, 5],[5, 4, 3, 2, 1]] )
print (arr02)
print(arr02.shape)

[[1 2 3 4 5]
 [5 4 3 2 1]]
(2, 5)


In [27]:
## Inbuilt Funcation

np.arange(1,10,2).reshape(5,1)


array([[1],
       [3],
       [5],
       [7],
       [9]])

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
## identity function
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [34]:
## Attributes of Numpy Array
arr02=np.array([[1, 2, 3, 4, 5],[5, 4, 3, 2, 1]] )
print ("Array:\n", arr02)
print("Shape:", arr02.shape)
print("Dimension:", arr02.ndim)
print("Size:", arr02.size)
print("Data Type:", arr02.dtype)
print("item size in bytes", arr02.itemsize)

Array:
 [[1 2 3 4 5]
 [5 4 3 2 1]]
Shape: (2, 5)
Dimension: 2
Size: 10
Data Type: int64
item size in bytes 8


In [42]:
 ## Numpy Vectorized Operation
#1- Addition
#2- Substraction
#3- Multiplication
#4- Divison

arr01=np.array([1, 3, 5, 7, 9])
arr02=np.array([2, 4, 6, 8, 10])
print("01. Addition of elements:", arr01 + arr02)
print("02. Subtraction of elements:", arr01 - arr02)
print("03. Multiplication of elements:", arr01 * arr02)
print("04. Division of elements:", arr01 / arr02)


01. Addition of elements: [ 3  7 11 15 19]
02. Subtraction of elements: [-1 -1 -1 -1 -1]
03. Multiplication of elements: [ 2 12 30 56 90]
04. Division of elements: [0.5        0.75       0.83333333 0.875      0.9       ]


In [45]:
## Universal Function
#1- Square Root (sqrt)
#2- Exponential (exp)
#3- Sine (sin)
#4- Natural Log (log)

arr01=np.array([10, 15, 30, 35, 70])
print("01.  root of Array-01:", np.sqrt(arr01))
print("02. Exponent of Array-01:", np.exp(arr01))
print("03. Sine of Array-01:", np.sin(arr01))
print("04. Natural log of Array-01:", np.log(arr01))



01.  root of Array-01: [3.16227766 3.87298335 5.47722558 5.91607978 8.36660027]
02. Exponent of Array-01: [2.20264658e+04 3.26901737e+06 1.06864746e+13 1.58601345e+15
 2.51543867e+30]
03. Sine of Array-01: [-0.54402111  0.65028784 -0.98803162 -0.42818267  0.77389068]
04. Natural log of Array-01: [2.30258509 2.7080502  3.40119738 3.55534806 4.24849524]


In [56]:
## Perfoming Various Operations
#01. Indexing
#02. Slicing
#03. Modifying
arr01=np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15]])
print("01. Array:\n", arr01)
print("02. (Row, Column):", arr01.shape)


01. Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
02. (Row, Column): (3, 5)


In [89]:
#01. Indexing
arr01[0][0]

np.int64(1)

In [61]:
arr01[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [69]:
arr01[1:,3:]

array([[ 9, 10],
       [14, 15]])

In [90]:
#Slicing
arr01=np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15]])

print("Array:\n", arr01)

print("01:-----------------------------------\n", arr01[0][0])

print("02:-----------------------------------\n", arr01[1:,3:])

print("03:-----------------------------------\n", arr01[0:2])

print("04:-----------------------------------\n", arr01[0:2,1:4])

print("05:-----------------------------------\n", arr01[1:,1:3])


Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
01:-----------------------------------
 1
02:-----------------------------------
 [[ 9 10]
 [14 15]]
03:-----------------------------------
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
04:-----------------------------------
 [[2 3 4]
 [7 8 9]]
05:-----------------------------------
 [[ 7  8]
 [12 13]]


In [99]:
#Modifying
arr01[0,3]=4
arr01[0,4]=5000
arr01[1,3]=9000
arr01[2,2]=13000
print("Modifyied array:\n", arr01)

Modifyied array:
 [[    1     2     3     4  5000]
 [    6     7     8  9000    10]
 [   11    12 13000    14    15]]


In [109]:
## Statical Concept--

#Normalization means to have a mean of 0 & standard devaition of 1

#Step01- Calculate the mean & standard Deviation 

#01. mean= np.mean(data)

#02. std_dev= np.std(data)

#Steo02- Normalize The data

# normalized_data = (data - mean)/ std_dev

data= np.array([10,15,30,35,70])
print("Array:\n",data)
print("-----------------------------------------------")

mean=np.mean(data)
print("Mean of Data:", mean)

print("-----------------------------------------------")

std_dev=np.std(data)
print("Std_Deviation of Data:", std_dev)

print("-----------------------------------------------")

normalized_data=(data -mean)/ std_dev
print("Normalized Data:", normalized_data)


Array:
 [10 15 30 35 70]
-----------------------------------------------
Mean of Data: 32.0
-----------------------------------------------
Std_Deviation of Data: 21.118712081942874
-----------------------------------------------
Normalized Data: [-1.04173019 -0.80497333 -0.09470274  0.14205412  1.79935215]


In [128]:
## Calculating:

#01- Mean
#02- Median
#03- Variance
#04- Max
#05- Min

data= np.array([10,2,20,4,50,6,70,8,90,1])
print("Array:\n", data)

print("-----------------------------------------------")

mean=np.mean(data)
print("Mean of Data:", mean)

print("-----------------------------------------------")

median=np.median(data)
print("Median of Data:", median)

print("-----------------------------------------------")

variance=np.var(data)
print("Variance of Data:", variance)

print("-----------------------------------------------")

std_dev=np.std(data)
print("Std_Deviation of Data:", std_dev)

print("-----------------------------------------------")

maximum=np.max(data)
print("Max of Data:", maximum)

print("-----------------------------------------------")

minimum=np.min(data)
print("Min of Data:", minimum)


Array:
 [10  2 20  4 50  6 70  8 90  1]
-----------------------------------------------
Mean of Data: 26.1
-----------------------------------------------
Median of Data: 9.0
-----------------------------------------------
Variance of Data: 930.89
-----------------------------------------------
Std_Deviation of Data: 30.510489999342848
-----------------------------------------------
Max of Data: 90
-----------------------------------------------
Min of Data: 1


In [125]:
## Logical Operation

data=np.array([3,7,13,16,17,19,20,24])
print("Array:\n", data)

print("-----------------------------------------------")

print("Value greter than 5 and less then 24 in array:",data[(data>=6) & (data <=23)])
print("Value greter than 5 and less then 24 in array:",data[(data>=6) | (data <=23)])

Array:
 [ 3  7 13 16 17 19 20 24]
-----------------------------------------------
Value greter than 5 and less then 24 in array: [ 7 13 16 17 19 20]
Value greter than 5 and less then 24 in array: [ 3  7 13 16 17 19 20 24]


# PANDAS LEARNING